version: 2.1
executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable
        auth:
          # ensure you have first added these secrets
          # visit app.circleci.com/settings/project/github/MrClogsworthYT/FNF-Cool-Engine/environment-variables
          username: $DOCKER_HUB_USER
          password: $DOCKER_HUB_PASSWORD
jobs:
  hello:
    executor: my-custom-executor
    steps:
      - checkout
      - run: |
                    haxelib setup C:/haxelib
                    haxelib install hxcpp > nul
                    haxelib install lime
                    haxelib install openfl
                    haxelib --never install flixel
                    haxelib run lime setup flixel
                    haxelib run lime setup
                    haxelib install flixel-tools
                    haxelib install flixel-ui
                    haxelib install flixel-addons
                    haxelib install tjson
                    haxelib install hxjsonast
                    haxelib install linc_luajit
                    haxelib install hscript
                    haxelib git hscript-ex https://github.com/ianharrigan/hscript-ex
                    haxelib git discord_rpc https://github.com/Aidan63/linc_discord-rpc
                    haxelib install hxcpp-debug-server
                    haxelib list
                    haxelib run lime build windows --app-version="4.0.0-${{ github.run_id}}"
workflows:
  my-custom-workflow:
    jobs:
      - hello