/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-102948-g79ebdbb9b9-20210711"
#endif /* AVUTIL_FFVERSION_H */
